package com.feature.neighbourHood_backend.controller;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.feature.neighbourHood_backend.service.SupabaseStorageService;

import io.jsonwebtoken.io.IOException;

//this is the api generated by ai for testing
@RestController
@RequestMapping("/api/files")
public class FileController {

    @Autowired
    private SupabaseStorageService storageService;

    @PostMapping("/upload")
    public ResponseEntity<?> uploadFile(@RequestParam("file") MultipartFile file) throws java.io.IOException {
        try {
            String url = storageService.uploadFile(file, "uploads");
            return ResponseEntity.ok(Map.of("message", "上传成功", "url", url));
        } catch (IOException e) {
            return ResponseEntity.status(500).body(Map.of("message", "上传失败: " + e.getMessage()));
        }
    }
}
